services:
  - type: web
    name: group-project-petly-backend
    env: node
    plan: free
    repo: https://github.com/yulyaolshanska/petly-backend
    branch: main
    buildCommand: yarn install
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        fromDatabase:
          name: mongodb.net/petly-project
          property: connectionString
